### ISSUE TITLE
It isn't a good idea to put each program in a folder named "program-NN"

### ISSUE THREAD

**Issue by pixelomer** [swaaz/basicprograms#121]
Programs should either not have their own directories or they should have directories that have a small description on what they do as their name. This will reduce merge conflicts and make it easier for people to find what they are looking for.

**Comment by swaaz** [comment]
That is why I am asking everyone to follow the folder structure. can @pixelomer create a folder structure and instruction to follow before creating pr

**Comment by ArjunBhandari-666** [comment]
Another suggestion could be to add a title of the Problem Program in the description of the uploaded program in the same structure as has been followed so far
