### ISSUE TITLE
Add list implementation in Python

### ISSUE THREAD

**Issue by nitinkumar30** [swaaz/basicprograms#252]
After going through the codes in python I got to know there is no code for list implementation that is also menu-driven. I'd like to contribute to this repo by adding list implementation in Python with some functionalities like traversal, insertion of single/multiple elements & deletion of elements when you know index no & when you know item value.

I thought of going with basic C language but before that, wanted to move ahead with Python first as my first pull request.

Please add this request as my Hacktober fest 2021 PR.

**Comment by swaaz** [comment]
Good one!!

**Comment by nitinkumar30** [comment]
> Good one!!

Thanks @swaaz bro

**Comment by nitinkumar30** [comment]
Hi @swaaz 
Please go through the Python/Program 32 which was contributed by me. It was re-registered with an LCM program. Please do the necessary changes in that so that my PR may not get disqualified. Thanks.
