### ISSUE TITLE
Implementing stack using array & linked list in C language

### ISSUE THREAD

**Issue by nitinkumar30** [swaaz/basicprograms#254]
I've gone through the repo & it seems there isn't a code for **implementing stack using array & linked list**. It's an important DSA question which almost every interviewer asks for. I have a code written in C language which I'd like to contribute to. 

I wanted to contribute mostly in Python language but DSA is also important for interview preparation.

Please tag this issue under 'Hacktober fest 2021'.

**Comment by swaaz** [comment]
Do create a separate folder called interview questions and add under that. It will be helpful for others too. @nitinkumar30

**Comment by AyushSingh-github** [comment]
hey @swaaz ! this is my first hactoberfest . i would like to contribute with this repo . i already did my first part for pull request where i used graphs dsa with python. i need to complete my other 3 pull request. can you help me with my other pull request as i wish to add my headphone website along with other c and java dsa problems so that i can complete my fest this time as im not good with git and dont know how to make a good readme file.

**Comment by udaysk3** [comment]
hello @swaaz ! like @AyushSingh-github, this is also my first hacktoberfest. I would like to contribute to this repository. I am confident that I can complete this issue by Implementing stack using array & linked list in C language in which I have learned DSA.
Thank You!!!!.

**Comment by swaaz** [comment]
@AyushSingh-github @udaysk3 Great!! Do add new programs and bot to forget to add readme file. Watch my [tutorial](https://youtu.be/MfYykauWmSo) to master Git and GitHub.

**Comment by nitinkumar30** [comment]
> hello @swaaz ! like @AyushSingh-github, this is also my first hacktoberfest. I would like to contribute to this repository. I am confident that I can complete this issue by Implementing stack using array & linked list in C language in which I have learned DSA. Thank You!!!!.

Hi @udaysk3 , this topic has been already PR'ed by me. I don't think duplicate repo will be considered. Follow [this PR](https://github.com/swaaz/basicprograms/pull/270#issue-1014163794) for additional information.
CC - @swaaz

**Comment by udaysk3** [comment]
I have submitted another program. BTW thanks for your advice !

**Comment by nitinkumar30** [comment]
> I have submitted another program. BTW thanks for your advice !

better.
