### ISSUE TITLE
Tkinter project - Notepad with Python

### ISSUE THREAD

**Issue by nitinkumar30** [swaaz/basicprograms#294]
After carefully going through the repo, I was able to see Tkinter project was not there. I want to contribute it using some of my knowledge.

I'll be making a simple notepad using python's Tkinter module.

The features will include:

writing the text
saving the text as .txt file
opening any .txt file
Please tag this issue with 'hacktober fest 2021'

**Comment by swaaz** [comment]
@nitinkumar30 Unfortunately this repo is meant to have basic programs. I would appreciate it if you could add basic programs.

**Comment by nitinkumar30** [comment]
So @swaaz , I would like to add some simple programs. Please go through the list & assign me the necessary issue. Programs will be in Python language only.

- area of circle
- area of square
- area of rectangle

- Find the largest no in an array
- swapping of 2 elements in a list
- find number is even or odd
- print even nos in a certain range
- check palindrome string
- print vowels, consonants, special characters in a string

And if these are ok, assign this with tag 'Hacktober fest 2021'.
