### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by pilipi-puu-puu** [swaaz/basicprograms#305]
![ss_issue](https://user-images.githubusercontent.com/87390353/136076982-8fde8cb7-83f8-4122-9efd-9fb4df8848e7.jpg)

## "Click me" link is not working. It's showing this site can't be reached.

**Comment by swaaz** [comment]
Go ahead and fix all bugs!!! @pilipi-puu-puu

**Comment by pilipi-puu-puu** [comment]
@swaaz kindly provide me the proper link which you wanted to add on "Click me" . Then only I can fix the bug.😊

**Comment by swaaz** [comment]
@pilipi-puu-puu https://gitgo.swaaz.dev/
