### ISSUE TITLE
Creating/Updating README.md of major directories

### ISSUE THREAD

**Issue by NamanManjkhola** [swaaz/basicprograms#306]
# Description
Completing list of C++, Java, python, C program on  README.md/Creating README.md for Dart, Kotlin, Javascript and adding link for the same to access them easily.
# screenshot
![aa](https://user-images.githubusercontent.com/77687018/136079016-557a9ab1-cfc9-4acf-ada9-1156fbc8337f.JPG)

**Comment by NamanManjkhola** [comment]
Hey @swaaz I'm hactoberfest participant. Can I work on this issue?

**Comment by swaaz** [comment]
Yea sure you can work but try to update all readme @NamanManjkhola

**Comment by NamanManjkhola** [comment]
Every Directory's readme?

**Comment by swaaz** [comment]
@NamanManjkhola Yep if possible.

**Comment by NamanManjkhola** [comment]
Okay. I'll do it

**Comment by NamanManjkhola** [comment]
@swaaz  please add the name in assignees and add Hacktoberfest tag.

**Comment by NamanManjkhola** [comment]
@swaaz I need to commit changes to hacktoberfest branch right?
